services:

  client:
    build: ./client
    container_name: react_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  
  db:
    build: ./db
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${db_username}
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_DB=${db_name}